# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'large_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 505)
        MainWindow.setStyleSheet("QMainWindow{border-image:url(:/newPrefix/game_background.png);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.display_window = QtWidgets.QLabel(self.centralwidget)
        self.display_window.setObjectName("display_window")
        self.verticalLayout.addWidget(self.display_window)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 6, 10, -1)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previous = QtWidgets.QPushButton(self.centralwidget)
        self.previous.setStyleSheet("QPushButton{background:#F7D674;border-radius:5px;}QPushButton:hover{background:rgb(255, 255, 127);}\n"
"")
        self.previous.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous.setIcon(icon)
        self.previous.setIconSize(QtCore.QSize(32, 32))
        self.previous.setObjectName("previous")
        self.horizontalLayout.addWidget(self.previous)
        self.individual = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.individual.sizePolicy().hasHeightForWidth())
        self.individual.setSizePolicy(sizePolicy)
        self.individual.setObjectName("individual")
        self.horizontalLayout.addWidget(self.individual)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setStyleSheet("QPushButton{background:#F7D674;border-radius:5px;}QPushButton:hover{background:rgb(255, 255, 127);}\n"
"")
        self.next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/right_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon1)
        self.next.setIconSize(QtCore.QSize(32, 32))
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.results = QtWidgets.QLabel(self.centralwidget)
        self.results.setObjectName("results")
        self.horizontalLayout.addWidget(self.results)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 6)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Open Sheep Face"))
        self.title.setText(_translate("MainWindow", "Sheep Face Analyzer"))
        self.display_window.setText(_translate("MainWindow", "TextLabel"))
        self.individual.setText(_translate("MainWindow", "TextLabel"))
        self.results.setText(_translate("MainWindow", "TextLabel"))
        self.logo.setText(_translate("MainWindow", "TextLabel"))
import large_window_rc
